name: Docker Image CI

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login Registry
        env:
          REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
          REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
        run: |
          echo "${REGISTRY_PASSWORD}" | docker login -u ${REGISTRY_USERNAME} go-to-cloud-docker.pkg.coding.net --password-stdin
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            go-to-cloud-docker.pkg.coding.net/release/go-to-cloud/gtc-frontend:${{github.ref_name}}
